# Generated by Django 3.2.5 on 2021-07-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lang',
            field=models.CharField(choices=[('English', 'en'), ('French', 'fr'), ('Russian', 'ru')], default='en', max_length=9),
        ),
    ]
