# Generated by Django 3.2.5 on 2021-07-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_event_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lang',
            field=models.CharField(choices=[('en', 'en'), ('fr', 'fr'), ('fr', 'ru')], default='en', max_length=9),
        ),
    ]
