# Generated by Django 3.2.5 on 2021-07-18 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=500)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(upload_to='songs/')),
                ('song', models.FileField(upload_to='')),
            ],
        ),
    ]
