# Generated by Django 3.2.5 on 2021-07-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='lang',
            field=models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Russian', 'Russian')], default='English', max_length=9),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_keywords',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='images/news/'),
        ),
    ]
