# Generated by Django 3.2.5 on 2021-07-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/members/')),
                ('role', models.CharField(blank=True, max_length=150, null=True)),
                ('lang', models.CharField(choices=[('English', 'English'), ('French', 'French'), ('Russian', 'Russian')], default='English', max_length=9)),
                ('biograph', models.TextField()),
                ('linkedin', models.CharField(blank=True, max_length=150, null=True)),
                ('twitter', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook', models.CharField(blank=True, max_length=150, null=True)),
                ('instagram', models.CharField(blank=True, max_length=150, null=True)),
                ('soundcloud', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
